
/*
   List of node names ( identifiers ).
*/

interface Nodes {
static final short 
N_EMPTY 			=  0 , 
// unused 			=  1 , 
N_AND 				=  2 ,
N_CLAUSE_OP		 	=  3 ,	
N_BETWEEN 			=  4 ,
N_UNARY_SUBTRACT	=  5 ,
// unused			=  6 ,
N_NOT_IN 			=  7 ,
N_IN 				=  8 , 
N_DEFAULT_VALUE		=  9 ,	 
N_FALSE 			= 10 , 
N_TRUE 				= 11 , 	
N_NOT 				= 12 , 
N_NULL 				= 13 , 
N_OR 				= 14 ,
N_XOR 				= 15 ,
N_UNION  			= 16 ,			
// unused			= 17 ,
N_PLUS  			= 18 ,
N_SUBTRACT  		= 19 ,
N_MULTIPLY  		= 20 ,
N_DIVIDE 			= 21 ,
N_EQUAL 			= 22 ,
N_GT 				= 23 ,
N_LT 				= 24 ,
N_MEMBERSHIP 		= 25 ,
N_N_EQUAL 			= 26 ,
N_GT_EQUAL 			= 27 ,
N_LT_EQUAL 			= 28 ,
N_CONCAT 			= 29 ,
N_TYPE_COMPONENT 	= 30 ,
N_TYPE_RULESET		= 31 ,
N_FLOW_TO_STOCK 	= 32 ,		
N_STOCK_TO_FLOW		= 33 ,		
N_NUMBER 			= 34 ,
N_STRING 			= 35 ,
N_IDENTIFIER		= 36 ,
N_FILL_TIME_SERIES 	= 37 ,	
// unused 			= 38 ,
N_CLAUSE_SUBSCRIPT 	= 39 ,
N_EXISTS_IN 		= 40 ,
N_PERIOD_INDICATOR	= 41 ,
N_PARENTHESIS 		= 42 ,
N_SQL_ROW_FUNCTION 	= 43 ,
N_SQL_AGGREGATE_FUNCTION= 44 ,
N_SQL_ANALYTIC_FUNCTION = 45 ,
N_GROUP_BY 			= 46 ,
N_GROUP_EXCEPT 		= 47 ,
N_DUMMY 			= 48 ,
N_SORT_ASC_DESC		= 49 ,
// unused 			= 50 ,	
N_GROUP_ALL			= 51 ,	
N_ORDER_BY 			= 52 ,
N_PARTITION_BY 		= 53 ,
N_TYPE_DATASET		= 54 ,
N_TYPE_SCALAR 		= 55 ,
N_USER_TYPE 		= 56 ,
N_CAST		 		= 57 ,
N_TIMESHIFT 		= 58 ,
N_TYPE_CONSTRAINT	= 59 ,
N_TYPE_NULL 		= 60 ,
// unused 			= 61 ,	 
// unused 			= 62 ,
// unused 			= 63 ,	
// unused 			= 64 ,	
N_POSITION 			= 65 ,
N_SET_SCALAR 		= 66 ,	
N_CLAUSE_APPLY		= 67 ,	
N_TYPE_SET 			= 68 ,
N_COMPONENT_LIST 	= 69 ,	
// unused 			= 70 ,	
N_SYMDIFF 			= 71 ,
N_IF 				= 72 ,	
N_VTL_META_DATASET 	= 73 ,
N_GENERIC_COMPONENT	= 74 ,
N_COMPONENT 		= 75 ,	
N_VARIABLE 			= 76 ,
N_CHECK 			= 77 ,
N_CHECK_DATAPOINT 	= 78 ,
N_CHECK_HIERARCHY	= 79 ,		
N_INTERSECT 		= 80 ,
N_JOIN_ARGUMENTS	= 81 ,
N_ISNULL			= 82 ,				
N_MATCH_CHARACTERS 	= 83 ,
N_USER_OPERATOR_CALL = 84 ,	
N_HIERARCHY 		= 85 ,			
N_TIME_AGG 			= 86 ,
N_SETDIFF 			= 87 , 					
N_VTL_ASSIGNMENT 	= 88 ,
N_EVAL			 	= 89 ,			
N_JOIN		 		= 90 ,
N_CLAUSE_ASSIGNMENT	= 91 ,
N_CLAUSE_AGGR		= 92 ,		
N_CLAUSE_CALC 		= 93 ,
N_CLAUSE_DROP 		= 94 ,
N_CLAUSE_FILTER 	= 95 ,
N_CLAUSE_KEEP 		= 96 ,
N_CLAUSE_RENAME 	= 97 ,
N_CLAUSE_PIVOT 		= 98 ,
N_CLAUSE_UNPIVOT 	= 99 ;
// 100-299 reserved for the statements



}
